# 42 Inception docker-compose configuration
version: "3.7" #optional, can be changed depends

volumes:
  mariadb:
    driver: local
    driver_opts:
      device: /home/fech-cha/data
      o: bind
      type: none
  wordpress:
    driver: local
    driver_opts:
      device: /home/fech-cha/data
      o: bind
      type: none
  
networks:
  inception:
    name: inception
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/16

services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb #test tag :inception or :latest
    # ports: don't need to map those containers
    ports:
      - 3306
    networks:
      inception:
        ipv4_address: 198.168.1.2
    volumes:
      - "mariadb:/var/lib/mysql"
    restart: "on-failure"
    container_name: "mariadb"
  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    ports:
      - 9000
    networks:
      inception:
        ipv4_address: 198.168.1.3
    volumes:
      - "wordpress:/var/www/html"
    restart: "on-failure"
    depends_on:
      - mariadb
    container_name: "wordpress"
  nginx:
    build: ./requirements/nginx
    image: nginx
    ports:
      - "443:443"
    networks:
      inception:
       ipv4_address: 198.168.1.4
    volumes:
      - "wordpress:/var/www/html"
    restart: "on-failure"
    depends_on:
      - wordpress
    container_name: "nginx"
  adminer:
    build: ./requirements/bonus/adminer
    image: adminer
    ports: 
    networks:
      inception:
        ipv4_address: 198.168.1.5
    volumes:
      - "mariadb:/var/lib/mysql"
    restart: "on-failure"
    depends_on:
      - mariadb
    container_name: "adminer"
  ftp:
  redis:
  website:
  extra:


