# 42 Inception docker-compose configuration
version: "3.7" #optional, can be changed depends

volumes:
  mariadb:
    driver: local
    driver_opts:
      device: /home/fech-cha/data/mariadb
      o: bind
      type: none
  wordpress:
    driver: local
    driver_opts:
      device: /home/fech-cha/data/wordpress
      o: bind
      type: none

  
networks:
  inception:
    name: inception
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/16

services:
  mariadb:
    env_file:
      - .env
    build: ./requirements/mariadb
    image: mariadb #test tag :inception or :latest
    # ports: don't need to map those containers
    ports:
      - "3306:3306"
    networks:
      inception:
        ipv4_address: 198.168.1.2
    volumes:
      - "mariadb:/var/lib/mysql"
    restart: "on-failure"
    container_name: "mariadb"
  wordpress:
    env_file:
      - .env
    build: ./requirements/wordpress
    image: wordpress
    ports:
      - "9000:9000"
    networks:
      inception:
        ipv4_address: 198.168.1.3
    volumes:
      - "wordpress:/var/www/html"
    restart: "on-failure"
    depends_on:
      - mariadb
    container_name: "wordpress"
  nginx:
    env_file:
      - .env
    build: ./requirements/nginx
    image: nginx
    ports:
      - "443:443"
    networks:
      inception:
       ipv4_address: 198.168.1.4
    volumes:
      - "wordpress:/var/www/html"
    restart: "on-failure"
    depends_on:
      - wordpress
    container_name: "nginx"
  adminer:
    env_file:
      - .env
    build: ./requirements/bonus/adminer
    image: adminer
    ports:
      - "1234:1234"
    networks:
      inception:
        ipv4_address: 198.168.1.5
    volumes:
      - "mariadb:/var/lib/mysql"
    restart: "on-failure"
    depends_on:
      - mariadb
    container_name: "adminer"
  sftp:
    env_file:
      - .env
    build: ./requirements/bonus/sftp
    image: sftp
    ports:
      - "21:21"
    networks:
      inception:
        ipv4_address: 198.168.1.6
    volumes:  
      - "wordpress:/var/www/html"
    restart: "on-failure"
    container_name: "sftp"
  portfolio:
    env_file:
      - .env
    build: ./requirements/bonus/portfolio
    image: portfolio
    ports:
      - "5000:5000"
    networks:
      inception:
        ipv4_address: 198.168.1.7
    restart: "on-failure"
  # redis:
  # cadvisor:


