# 42 Inception docker-compose configuration
version: "3.7" #optional, can be changed depends

#Volumes section
volumes:
  mariadb:
    driver: local
    driver_opts:
      device: /home/fech-cha/data/mariadb
      o: bind
      type: none

  wordpress:
    driver: local
    driver_opts:
      device: /home/fech-cha/data/wordpress
      o: bind
      type: none

#Networks section
networks:
  inception:
    name: inception
    driver: bridge
    ipam:
      config:
        - subnet: 198.168.0.0/16

#Containers section
services:

  #Mariadb section
  mariadb:
    env_file:
      - .env
    build:
      context: ./requirements/mariadb
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_ROOT_PASS: ${DB_ROOT_PASS}
        DB_USER_PASS: ${DB_USER_PASS}
        DB_HOST: ${DB_HOST}
    image: mariadb #test tag :inception or :latest
    ports:
      - "3306:3306"
    networks:
      inception:
        ipv4_address: 198.168.0.2
    volumes:
      - "mariadb:/var/lib/mysql"
    restart: "always"
    container_name: "mariadb"

  #Wordpress section
  wordpress:
    env_file:
      - .env
    build: 
      context: ./requirements/wordpress
      args:
        DB_USER: ${DB_USER}
        DB_NAME: ${DB_NAME}
        DB_HOST: ${DB_HOST}
        DB_USER_PASS: $(DB_USER_PASS)
        WP_TITLE: ${WP_TITLE}
        WP_EMAIL: ${WP_EMAIL}
        WP_PASS: ${WP_PASS}
        WP_USER: ${WP_USER}
        USR: ${USR}
        USER_EMAIL: ${USER_EMAIL}
        USER_PASSWORD: ${USER_PASSWORD}
        RD_PASS: ${RD_PASS}
    image: wordpress
    ports:
      - "9000:9000"
    networks:
      inception:
        ipv4_address: 198.168.0.3
    volumes:
      - "wordpress:/var/www/html/"
    restart: "always"
    depends_on:
      - mariadb
    container_name: wordpress

  #Nginx Section
  nginx:
    env_file:
      - .env
    build: ./requirements/nginx
    image: nginx
    ports:
      - "443:443"
    networks:
      inception:
       ipv4_address: 198.168.0.4
    volumes:
      - "wordpress:/var/www/html/"
    restart: "always"
    depends_on:
      - wordpress
    container_name: "nginx"

  #Adminer section
  adminer:
    env_file:
      - .env
    build: ./requirements/bonus/adminer
    image: adminer
    ports:
      - "1234:1234"
    networks:
      inception:
        ipv4_address: 198.168.0.5
    volumes:
      - "mariadb:/var/lib/mysql"
    restart: "always"
    depends_on:
      - mariadb
    container_name: "adminer"

  #Portfolio (static website)
  portfolio:
    env_file:
      - .env
    build: ./requirements/bonus/portfolio
    image: portfolio
    ports:
      - "5000:5000"
    networks:
      inception:
        ipv4_address: 198.168.0.7
    restart: "always"
    container_name: "portfolio"

  #portainer section
  portainer:
    env_file:
      - .env
    build: ./requirements/bonus/portainer
    image: portainer
    ports:
      - "9443:9443"
    networks:
      inception:
        ipv4_address: 198.168.0.8
    volumes:
      - "/home/fech-cha/data/portainer:/data"
      - "/etc/localtime:/etc/localtime:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart: "always"
    container_name: "portainer"

  # redis:
  redis:
    env_file:
      - .env
    build: 
      context: ./requirements/bonus/redis
      args:
        RD_PASS: ${RD_PASS}
    image: redis
    ports:
      - "6969:6969"
    networks:
      inception:
        ipv4_address: 198.168.0.9
    volumes:
      - "wordpress:/var/www/html/"
    restart: "always"
    container_name: "redis"

